apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: api-carlos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-container
        image: localhost:5000/servicios-cloud-carlos:2        
        ports:
        - containerPort: 3000
