apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: api-carlos
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001
  type: NodePort
